services:
  - type: web
    name: cndpepci
    env: python
    buildCommand: pip install gunicorn && pip install -r requirements.txt
    startCommand: gunicorn app:app --log-file=-
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: DATABASE_URL
        value: mysql://cp679342p19_cndpep:Cndpep2024@@localhost:3306/cp679342p19_cndpep
    healthCheckPath: /sante
