"""add description and update member columns

Revision ID: 325c72f561da
Revises: c6645734c7a2
Create Date: 2024-12-04 18:00:55.252690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325c72f561da'
down_revision = 'c6645734c7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('domains',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('certifications',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_column('role')
        batch_op.drop_column('address')
        batch_op.drop_column('experience_years')
        batch_op.drop_column('longitude')
        batch_op.drop_column('website')
        batch_op.drop_column('latitude')
        batch_op.drop_column('license_number')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('license_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('certifications',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('domains',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
