"""restore previous member columns

Revision ID: 691ae65026bf
Revises: 325c72f561da
Create Date: 2024-12-04 18:05:51.139876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691ae65026bf'
down_revision = '325c72f561da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('license_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('domains',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('certifications',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.alter_column('certifications',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('domains',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('website')
        batch_op.drop_column('experience_years')
        batch_op.drop_column('license_number')
        batch_op.drop_column('role')
        batch_op.drop_column('bio')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
